### PR TITLE
[BUG] Incompatibility with deltalake v0.19.0 and above - failure in write_deltalake() #2753

### PR DESCRIPTION
**Pull request by igor-pechersky**
https://github.com/Eventual-Inc/Daft/issues/2753

### CODE REVIEW

**Comment by igor-pechersky** [comment]
this PR conflicts with https://github.com/Eventual-Inc/Daft/pull/2704 and overrides it

**Comment by samster25** [comment]
hi @igor-pechersky! Thanks for contribution. Do you mind sharing the error you receiving prior to this PR?

Looks like we have a test cast failing because the data schema and table schema differ
```
Data schema:
a: int64
b: double
c: string
d: binary
```
vs 
```
Table Schema:
a: int64
b: double
c: large_string
d: large_binary
```

We may need to still perform a manual cast to non-large dtypes

**Comment by igor-pechersky** [comment]
https://github.com/Eventual-Inc/Daft/pull/2754#issuecomment-2316959524
hi @samster25 
> Do you mind sharing the error you receiving prior to this PR?
https://github.com/Eventual-Inc/Daft/issues/2753

> We may need to still perform a manual cast
https://github.com/Eventual-Inc/Daft/commit/dc6c75bcabb4bd47e0746df083ed5b48ab68d8e1

**Comment by djouallah** [comment]
try large_dtypes=True when writing to delta

**Comment by igor-pechersky** [comment]
@djouallah 
see https://github.com/delta-io/delta-rs/commit/5e55cfbb9af49bc57900032313b5deee3d8ef08a#diff-8cf13a20f8e3f8d6b75c9fa25af0a006bf9806623721d15b9bc5fe9f260ac3b2L20

**Comment by kevinzwang** [comment]
Hi @igor-pechersky I didn't realize that we already had a PR open for this issue before I made #2827 😄 

Thanks for contributing this! However I think I would prefer to merge in my PR instead because it maintains compatibility with past deltalake versions.

**Comment by kevinzwang** [comment]
Closing this because we are merging in #2827!

**Comment by jaychia** [comment]
Thanks @igor-pechersky for taking a stab at this!

**Pull request closed without merging**
