### PR TITLE
[FEAT] add register-table helper to sql-catalog

### PR DESCRIPTION
**Pull request by chuanlei-coding**

### CODE REVIEW

**Comment by jaychia** [comment]
Hi, what's the intended use-case/ticket that this would address?

cc @universalmind303 as well who is designing the overall story for SQL

**Comment by chuanlei-coding** [comment]
@jaychia @universalmind303 so we can sql query dataframe on the fly.

**Comment by universalmind303** [comment]
Sorry @chuanlei-coding, It appears I overlooked this PR. if you want to fix the merge conflicts, I think we could get this in!

**Comment by chuanlei-coding** [comment]
> Sorry @chuanlei-coding, It appears I overlooked this PR. if you want to fix the merge conflicts, I think we could get this in!

@universalmind303 conflict fixed. Could you please have a look again?

**Review by universalmind303 — APPROVED** [review]

**Pull request merged**
