### PR TITLE
[BUG]: ide completions for expr namespaces

### PR DESCRIPTION
**Pull request by universalmind303**
closes https://github.com/Eventual-Inc/Daft/issues/2366

image

### CODE REVIEW

**Comment by universalmind303** [comment]
CI failure looks like a flake https://github.com/Eventual-Inc/Daft/actions/runs/9502021439/job/26189671812?pr=2374 and unrelated to PR.

**Comment by samster25** [comment]
Just retirggered the CI run, IDK why github actions have been so flaky lately. @jaychia Can you take a look?

**Review by jaychia — APPROVED** [review]
😮 thanks for catching this! I added a bunch of logic to fix the REPL autocomplete, but I guess it made the IDE autocomplete funky

**Comment by jaychia** [comment]
BTW It seems that this PR fixes autocomplete for IDEs, but breaks it for the REPL..

Autocomplete in the REPL uses the jedi library, which IIRC has some corner-casing around the name of the `@property` decorator being named exactly `"property"`... See https://github.com/Eventual-Inc/Daft/pull/2251 for where I originally tried to fix it.

**Pull request merged**
