### PR TITLE
[CHORE]: remove daft-table dependency from daft-logical-plan

### PR DESCRIPTION
**Pull request by universalmind303**
depends on https://github.com/Eventual-Inc/Daft/pull/3250

see https://github.com/Eventual-Inc/Daft/compare/kevin/swap-plan-scan-dependency...universalmind303:Daft:logical-plan-table-dep?expand=1 for proper diff

### CODE REVIEW

**Comment by universalmind303** [comment]
[this](https://github.com/Eventual-Inc/Daft/compare/kevin/swap-plan-scan-dependency...universalmind303:Daft:logical-plan-table-dep?expand=1#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R123-R126) might be too aggressive, but it doesn't seem to have much impact on the overall build time so i think it's fine.

**Comment by kevinzwang** [comment]
@universalmind303 could you rebase off of main now that my branch is merged
?

**Comment by universalmind303** [comment]
> @universalmind303 could you rebase off of main now that my branch is merged?

@kevinzwang this should be good to go now!

**Review by kevinzwang — APPROVED** [review]
LGTM!

**Pull request merged**
