### PR TITLE
[BUG] Implement deserialize for Python objects serialized as sequences

### PR DESCRIPTION
**Pull request by kevinzwang**
`visit_seq` is used when using serde_json to serialize/deserialize Rust objects, since the byte buffer is just stored as a list of numbers in JSON.

### CODE REVIEW

**Review by jaychia — APPROVED** [review]
Seems fine, but should we really be using JSON as the serde mechanism instead of bytes?

**Comment by kevinzwang** [comment]
> Seems fine, but should we really be using JSON as the serde mechanism instead of bytes?

I had this question too, but we can address that later. @samster25 wrote the IO Config pickling so maybe he should know the rationale.

**Comment by samster25** [comment]
> I had this question too, but we can address that later. @samster25 wrote the IO Config pickling so maybe he should know the rationale.

I did `serde_json` at the start since we all had were ints and strings and it was easy to read as a human and debug. However given that we now have bytes, pickles and whatnot inside of the payload, I think it makes sense to just encode it as bytes instead.

**Comment by jaychia** [comment]
@kevinzwang maybe good as a quick follow-up to switch us to using bytes

**Comment by kevinzwang** [comment]
> @kevinzwang maybe good as a quick follow-up to switch us to using bytes

https://github.com/Eventual-Inc/Daft/pull/3400 PTAL!

**Pull request merged**
