### PR TITLE
[FEAT] added max_bytes to parquets

### PR DESCRIPTION
**Pull request by dioptre**
This is important to guard from OOM exceptions. We have a lot of queries and need to improve determinism.

### CODE REVIEW

**Comment by dioptre** [comment]
Any word on this? Would love to see it in the main repo otherwise will need to fork permanently.

**Comment by jaychia** [comment]
Hi @dioptre ,would the following API work for you instead?

```python
filepaths_df = daft.from_glob_paths("s3://my-files/**.parquet")
filepaths_df = filepaths_df.where(filepaths_df["size"] < 1_000_000_000)  # filter only for filepaths that point to files less than 1GB in size
parquet_df = daft.read_parquet(filepaths_df["path"])  # read parquet files from a column in an existing dataframe
```

Adding this guard to the read API feels a little weird, since this should really be a "filter on the files that were globbed".

**Comment by dioptre** [comment]
We generally have very specific set of files we need to pass as an array per the fetch parquet api and don't want to double hop to s3. So unfortunately the glob wont work.

Thanks

**Comment by jaychia** [comment]
> We generally have very specific set of files we need to pass as an array per the fetch parquet api and don't want to double hop to s3. So unfortunately the glob wont work.
> 
> Thanks

We can also support `daft. from_glob_paths(["s3://file1.parquet", "s3://file2.parquet"])` very easily!

**Comment by dioptre** [comment]
Isn’t that still a double hop?

**Comment by dioptre** [comment]
Can we add support for the files you mentioned?

**Pull request closed without merging**
