### PR TITLE
[FEAT]: `daft.sql_expr`

### PR DESCRIPTION
**Pull request by universalmind303**
adds ability to use sql exprs for selecting columns.

ex
```py
df.where(daft.sql_expr('a > 1'))
```

### CODE REVIEW

**Comment by jaychia** [comment]
Omg so cool!!

**Review by kevinzwang — APPROVED** [review]
LGTM!

**Comment by samster25** [comment]
Sweet! quick question when do you think we could support
```
df.where('a > 1')
```
like [you can do in spark](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.filter.html#pyspark.sql.DataFrame.filter)

**Comment by universalmind303** [comment]
> Sweet! quick question when do you think we could support
> 
> ```
> df.where('a > 1')
> ```
> 
> like [you can do in spark](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.filter.html#pyspark.sql.DataFrame.filter)

I think we could now if we want. we could check if the input is a string, if so, delegate to `sql_expr`

**Pull request merged**
