### PR TITLE
[FEAT] connect: collect

### PR DESCRIPTION
**Pull request by andrewgazelka**

### CODE REVIEW

**Comment by andrewgazelka** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3326?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3326** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3326?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3326?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3308** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3308?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#3309](https://github.com/Eventual-Inc/Daft/pull/3309) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3309?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#3340](https://github.com/Eventual-Inc/Daft/pull/3340) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3340?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by kevinzwang** [comment]
@andrewgazelka should this PR have the implementation of `collect` in it? I only see the test

**Comment by andrewgazelka** [comment]
It is implemented as part of the client library and not the server, so we need no implementation to get it to work.

**Review by kevinzwang — APPROVED** [review]
LGTM

**Comment by andrewgazelka** [comment]
### Merge activity

* **Nov 20, 7:38 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3326).

**Pull request merged**
