### PR TITLE
[BUG] Fix empty struct fields

### LINKED ISSUE #1821: [BUG] Cannot read JSON with empty struct field
**Describe the bug**

Reading of JSONs will break with a panic if one of the struct fields was detected as having no fields.

```python
with open("data.json", "w") as f:
    f.write('{"foo": {}}\n')
    f.write('{"foo": {}}\n')

df = daft.read_json("data.json")
df.show()
```

This results in:

```
ScanWithTask-LocalLimit [Stage:4]:   0%|                                                                                                                                                  | 0/1 [00:00<?, ?it/s]thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("A StructArray must contain at least one field")', src/daft-json/src/decoding.rs:118:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
[1]    19848 abort      ipython
/Users/jaychia/.pyenv/versions/3.9.18/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown               
  warnings.warn('resource_tracker: There appear to be %d '
```

It seems like arrow2's `MutableStructArray` isn't very happy with structs that have empty fields... I wonder if this necessitates that we add some kind of placeholder value in these structs.

### PR DESCRIPTION
**Pull request by colin-ho**
Closes #1821 

Fixes a few bugs that deal with empty structs.

- allow empty structs in JSONs
- allow nested empty structs from in-memory reads
- remove the `"":null` placeholder in repr
- remove the `"":null` placeholder upon egress to python

### CODE REVIEW

**Review by jaychia — APPROVED** [review]
Thanks!

**Comment by samster25** [comment]
Looks like you are having a failure with pyarrow 6.0.1 in CI

**Comment by colin-ho** [comment]
> Looks like you are having a failure with pyarrow 6.0.1 in CI

fixed

the tests were failing during a cast from struct(["":null]) to struct() to make a pyarrow table for equality check with a daft df.to_arrow() table. instead, i changed the og type to struct(), but check that the daft datatype is struct(["":null]) instead of struct()

**Comment by colin-ho** [comment]
theres a bug, will fix:

```
In [1]: import daft

In [2]: df = daft.from_pydict({"a":[{},None,None],"b":[1,2,3]})

In [3]: df = df.where(df["a"].is_null())

In [4]: df.show()
╭──────────┬───────╮
│ a        ┆ b     │                                                                                                                     
│ ---      ┆ ---   │
│ Struct[] ┆ Int64 │
╞══════════╪═══════╡
╰──────────┴───────╯

(No data to display: Materialized dataframe has no rows)
```

**Pull request merged**
