### PR TITLE
[CHORE] fix self clippy lints

### PR DESCRIPTION
**Pull request by andrewgazelka**

### CODE REVIEW

**Comment by samster25** [comment]
looks good, we should however also add this commit to ignore revs like we do with our last import formatting. This will help preserve the git blame.
https://github.com/Eventual-Inc/Daft/pull/2807

https://moxio.com/blog/ignoring-bulk-change-commits-with-git-blame/

**Comment by andrewgazelka** [comment]
@samster25 tbh I am kinda confused 

image

image

**Comment by samster25** [comment]
@andrewgazelka I believe github runs the CI on the post merge commit. I think you should be fine with rebasing and then merging real real fast

**Comment by andrewgazelka** [comment]
opening separate PR on this repo

**Pull request closed without merging**
