### PR TITLE
[FEAT] Infer Azure storage account from uri

### LINKED ISSUE #3142: Azure storage account not properly set for Unity Catalog
### Describe the bug

See conversation here: https://github.com/Eventual-Inc/Daft/issues/2903#issuecomment-2434385035

### To Reproduce

```python
>>> unity = UnityCatalog(endpoint=DATABRICKS_HOST,token=PAT_TOKEN_AZURE)
>>> unity_table_ext = unity.load_table("some_catalog.some_schema.some_table") 
>>> df_ext = daft.read_deltalake(unity_table_ext)
>>> df_ext.show()

DaftCoreException: DaftError::External Generic AzureBlob error: Azure Storage Account not set and is required.
 Set either `AzureConfig.storage_account` or the `AZURE_STORAGE_ACCOUNT` environment variable.
```

### Expected behavior

Daft sets Azure storage account and properly shows dataframe

### Component(s)

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinzwang**
Resolves #3142

This PR also adds a dependency for the `derive_builder` crate, which I'm hoping to introduce into our repo and use throughout our code to reduce builder boilerplate.

### CODE REVIEW

**Comment by kevinzwang** [comment]
@anilmenon14 could you check if the changes in this PR works? Let me know if you need any help with that

**Comment by anilmenon14** [comment]
Hi @kevinzwang , the changes look great to me! I did a quick build of this branch on my laptop and ran tests and they look great!
After the `make build` and `make .venv` steps on this branch, I ran the below commands in the Python REPL:

```
# This is the ideal set of steps for Azure
import os
import daft # Using version 0.3.9
from daft.unity_catalog import UnityCatalog

DATABRICKS_HOST = os.environ.get('DATABRICKS_HOST')
PAT_TOKEN_AZURE = os.environ.get('PAT_TOKEN_AZURE') 

unity = UnityCatalog(endpoint=DATABRICKS_HOST,token=PAT_TOKEN_AZURE)
unity_table_ext = unity.load_table("ucx_migrated.ucx_dst_external.external_dbfs_mounted") # This is an external table
df_ext = daft.read_deltalake(unity_table_ext)
df_ext.show()
```
This worked perfectly,by rendering the expected results of the Dataframe onto the screen !  🙌

I also did a quick regression test using an AWS environment to confirm there has been no unintended impact seen elsewhere and it still works well there too.

**Comment by kevinzwang** [comment]
@anilmenon14 thanks for testing it! One final thing I'd like to confirm is that your setup without these changes fails, AKA that the Azure storage account was not set elsewhere in your testing, and that it is properly determined by Daft with this PR.

**Comment by anilmenon14** [comment]
Hi @kevinzwang , your statements are correct. With the code in this PR on a shell session without any pre-set environment variables for the Azure storage account, it is now able to determine the storage account.
Just to be extra sure, I did a comparison test with a virtual environment with the code from this PR versus the v0.3.9 on separate shell sessions initiated with same environment variables of access token and Host URL. 
The code snippet only successfully works for the DataFrame `.show()` API in the code version from this PR.

**Comment by kevinzwang** [comment]
That's great to hear! Thank you again for such thorough testing. @raunakab please give this a review whenever you can

**Review by raunakab — APPROVED** [review]
Looks good to me!

**Pull request merged**
